import type { Metadata } from "next";
import { Amiri } from "next/font/google";
import "./globals.css";
 

const amiri = Amiri({
  subsets: ['arabic'],
  weight: ['400'],
});
 
export const metadata: Metadata = {
  title: "Najaa Project",
  description: "Generated by Gaza",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={amiri.className}>
      <body className="min-h-screen bg-background text-foreground font-amiri">
        <main>{children}</main>
      </body>
    </html>
  );
}